name: "push to docker"
on:
  workflow_run:
    workflows: ["run sast on docker"]
    types:
      - completed
jobs:
    sonar_scan:
        runs-on: ubuntu-latest
        steps:
            - name: docker_login
              uses: actions/checkout@v3
            - name: login_docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: build and push
              run: |
               docker build -t docker.io/rahulambaragonda/devsecops:1 .
               docker push docker.io/rahulambaragonda/devsecops:1