name: "push to docker"

on:
  workflow_run:
    workflows: ["run sast on docker"]
    types:
      - completed

env:
  VERSION: ${{ github.run_number }}

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t docker.io/rahulambaragonda/devsecops:${{ env.VERSION }} .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/rahulambaragonda/devsecops:${{ env.VERSION }}
          format: table
          exit-code: 2
          severity: CRITICAL,HIGH

      - name: Push Docker Image
        if: success()
        run: |
          docker push docker.io/rahulambaragonda/devsecops:${{ env.VERSION }}
