name: Docker Image Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Grype
      - name: Install Grype
        run: |
          curl -s https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo bash

      # Step 4: Pull the Docker image to be scanned
      - name: Pull Docker Image
        run: |
          docker pull docker.io/yourusername/yourimage:latest

      # Step 5: Save Docker Image as tarball
      - name: Save Docker Image as tarball
        run: |
          docker save -o dockerimage.tar docker.io/yourusername/yourimage:latest

      # Step 6: Run Grype to scan the Docker image tarball for vulnerabilities
      - name: Run Grype Scan
        run: |
          grype docker-archive://dockerimage.tar --fail-on critical --exit-code 0

      # Step 7: (Optional) Upload Grype scan report
      - name: Upload Grype Report
        uses: actions/upload-artifact@v3
        with:
          name: grype-report
          path: grype-report.txt
