name: "Run Container Scan on Super Mario Docker Image with Clair"

on:
  push:
    branches:
      - main

env:
  VERSION: $(( $(cat version.txt) + 1 ))

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/rahuldocker628/mariogitopsproject:${{ env.VERSION }}
          docker save -o supermariolatestdockerimage.tar docker.io/rahuldocker628/mariogitopsproject:${{ env.VERSION }}

      - name: Set up Clair (using latest version)
        run: |
          docker pull quay.io/projectquay/Clair v4
          docker run -d --name clair -p 6060:6060 -p 6061:6061 quay.io/projectquay/clair:latest

      - name: Run Clair vulnerability scan
        run: |
          # Download and configure clair-scanner
          curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 -o clair-scanner
          chmod +x clair-scanner
          
          # Run Clair scan (replace YOUR_RUNNER_IP with the correct IP)
          ./clair-scanner --ip YOUR_RUNNER_IP --report clair-report.json supermariolatestdockerimage.tar

      - name: Upload Clair Scan Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Clair-Report
          path: clair-report.json
